docker run --rm --name kong \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_PG_PASSWORD=kong" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -p 8000:8000 \
     -p 8443:8443 \
     -p 127.0.0.1:8001:8001 \
     -p 127.0.0.1:8444:8444 \
     -v /etc/localtime:/etc/localtime \
     -v /etc/timezone:/etc/timezone \
     -v /Users//develops/kong_lua_scripts/kong-plugins/sandan-ip-filter/schema.lua:/usr/local/share/lua/5.1/kong/plugins/sandan-ip-filter/schema.lua \
     -v /Users//develops/kong_lua_scripts/kong-plugins/sandan-ip-filter/handler.lua:/usr/local/share/lua/5.1/kong/plugins/sandan-ip-filter/handler.lua \
     -v /Users//develops/kong_lua_scripts/kong-plugins/sandan-auth/schema.lua:/usr/local/share/lua/5.1/kong/plugins/sandan-auth/schema.lua \
     -v /Users//develops/kong_lua_scripts/kong-plugins/sandan-auth/handler.lua:/usr/local/share/lua/5.1/kong/plugins/sandan-auth/handler.lua \
     -v /Users//develops/kong_lua_scripts/kong-plugins/sandan-log/schema.lua:/usr/local/share/lua/5.1/kong/plugins/sandan-log/schema.lua \
     -v /Users//develops/kong_lua_scripts/kong-plugins/sandan-log/handler.lua:/usr/local/share/lua/5.1/kong/plugins/sandan-log/handler.lua \
     -v /Users//develops/kong_lua_scripts/kong-plugins/constants.lua:/usr/local/share/lua/5.1/kong/constants.lua \
     kong:latest